#!/bin/bash
function combine() {
  pdftk A=$1 B=$2 cat $(echo "print(' '.join([f'B1-1 A{n}-{n}' for n in range(1, 71)]))" | python3) output "$3"
}

if [ -z $3 ]
then
  combine "$1" "$2" "combined.pdf"
else
  combine "$1" "$2" "$3"
fi
